driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6.9
  - name: centos-7.3
  - name: fedora-25

suites:
  - name: default
    run_list:
      - recipe[yum::default]
      - recipe[yum_test::test_globalconfig_two]
