# Encoding: utf-8

require 'spec_helper'

describe 'yum::resource-tester' do
  let(:chef_run) { ChefSpec::Runner.new(:step_into => ['yum_repository']).converge(described_recipe) }

  let(:test1_content) do
    '# Generated by Chef
# Local modifications will be overwritten.

[test1]
name=an test
baseurl=http://drop.the.baseurl.biz
enabled=1
gpgcheck=1
sslverify=1
'
  end

  let(:test2_content) do
    '# Generated by Chef
# Local modifications will be overwritten.

[unit-test-2]
name=test all the things!
baseurl=http://example.com/wat
cost=10
enabled=1
enablegroups=1
exclude=package1 package2 package3
failovermethod=priority
fastestmirror_enabled=true
gpgcheck=1
gpgkey=http://example.com/RPM-GPG-KEY-FOOBAR-1
http_caching=all
include=/some/other.repo
includepkgs=package4 package5
keepalive=1
metadata_expire=never
mirrorlist=http://hellothereiammirrorliststring.biz
mirror_expire=300
mirrorlist_expire=86400
priority=10
proxy=http://hellothereiamproxystring.biz
proxy_username=kermit
proxy_password=dafrog
retries=10
sslcacert=/path/to/directory
sslclientcert=/path/to/client/cert
sslclientkey=/path/to/client/key
sslverify=1
timeout=10
'
  end

  # The simplest case
  it 'creates yum_repository[test1]' do
    expect(chef_run).to create_yum_repository('test1')
  end

  it 'steps into yum_repository and creates template[/etc/yum.repos.d/test1.repo]' do
    expect(chef_run).to render_file('/etc/yum.repos.d/test1.repo').with_content(test1_content)
  end

  # Full blown parameterization. Exercercises the
  # recipe->resource->provider->template chain
  it 'creates yum_repository[test2]' do
    expect(chef_run).to create_yum_repository('test2')
  end

  it 'steps into yum_repository and creates template[/etc/yum.repos.d/unit-test-2.repo]' do
    expect(chef_run).to render_file('/etc/yum.repos.d/unit-test-2.repo').with_content(test2_content)
  end
end
